// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1r_MfhVlR4yn_EY_QPJPXN_rt0xQPnQ',
    appId: '1:502601666521:web:ee2f1886895e8625d7d3c8',
    messagingSenderId: '502601666521',
    projectId: 'devates-f549e',
    authDomain: 'devates-f549e.firebaseapp.com',
    storageBucket: 'devates-f549e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_WrUM9-L-OiEqIueZEKEuf9ZZGx7k8U',
    appId: '1:502601666521:android:f57ad7aedb4972ebd7d3c8',
    messagingSenderId: '502601666521',
    projectId: 'devates-f549e',
    storageBucket: 'devates-f549e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyOWIgLJ9tdssFAseyUc11tzVsUkcbuY',
    appId: '1:502601666521:ios:e185021dcfcb8fa5d7d3c8',
    messagingSenderId: '502601666521',
    projectId: 'devates-f549e',
    storageBucket: 'devates-f549e.appspot.com',
    iosBundleId: 'com.example.devates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbyOWIgLJ9tdssFAseyUc11tzVsUkcbuY',
    appId: '1:502601666521:ios:ac8022476c407abbd7d3c8',
    messagingSenderId: '502601666521',
    projectId: 'devates-f549e',
    storageBucket: 'devates-f549e.appspot.com',
    iosBundleId: 'com.example.devates.RunnerTests',
  );
}
